import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import { TodoProvider } from '@/contexts/TodoContext';
import NavList from '@/components/organisms/NavList';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TodoList',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodoProvider>
          <div className='container'>
            <NavList />
            {children}
          </div>
        </TodoProvider>
      </body>
    </html>
  )
}
